//
//  MPWMachOLinkerCharacterizationTests.m
//  ObjSTNative
//
//  Characterization tests for dylib generation
//  These tests compare our internal linker output against reference dylibs
//  generated by the external linker.
//

#import <MPWFoundation/MPWFoundation.h>
#import "MPWMachOReader.h"
#import "MPWMachOLinker.h"
#import "MPWMachODylibWriter.h"
#import "STNativeCompiler.h"
#import <mach-o/loader.h>

@interface MPWMachOLinkerCharacterizationTests : NSObject
@end

@implementation MPWMachOLinkerCharacterizationTests

#pragma mark - Helper Methods

+(void)codesignDylibAtPath:(NSString*)path
{
    NSTask *task = [[[NSTask alloc] init] autorelease];
    task.launchPath = @"/usr/bin/codesign";
    task.arguments = @[@"-f", @"-s", @"-", path];
    task.standardOutput = [NSPipe pipe];
    task.standardError = [NSPipe pipe];
    [task launch];
    [task waitUntilExit];
}

+(NSBundle*)testBundle
{
    return [NSBundle bundleForClass:self];
}

#pragma mark - Dylib Factories

+(MPWMachOReader*)readerForReferenceFramework
{
    NSURL *frameworkURL = [[self testBundle] URLForResource:@"ReferenceSTClass" withExtension:@"framework"];
    if (!frameworkURL) return nil;

    NSString *dylibPath = [[frameworkURL path] stringByAppendingPathComponent:@"ReferenceSTClass"];
    NSData *data = [NSData dataWithContentsOfFile:dylibPath];
    if (!data) return nil;

    return [[[MPWMachOReader alloc] initWithData:data] autorelease];
}

+(MPWMachOReader*)readerForInternalLinkerDylib
{
    STNativeCompiler *compiler = [STNativeCompiler compiler];
    NSString *source = @"class InternalLinkerTestClass : NSObject { -answerFortyTwo { 42. } -addFive:x { x + 5. } }";
    STClassDefinition *theClass = [compiler compile:source];
    [compiler compileClassToMachoO:theClass];

    MPWMachOLinker *linker = [[[MPWMachOLinker alloc] init] autorelease];
    NSData *dylib = [linker linkToDylibWithInstallName:@"@rpath/InternalLinkerTestClass.framework/InternalLinkerTestClass"
                                            fromWriter:(MPWMachOWriter*)compiler.writer];

    return [[[MPWMachOReader alloc] initWithData:dylib] autorelease];
}

#pragma mark - Shared Verification Methods

// Verifies basic Mach-O validity - same for both
+(void)verifyValidMachO:(MPWMachOReader*)reader name:(NSString*)name
{
    EXPECTTRUE(reader.isHeaderValid, ([NSString stringWithFormat:@"%@ should be valid Mach-O", name]));
    INTEXPECT([reader filetype], MH_DYLIB, ([NSString stringWithFormat:@"%@ should be a dylib", name]));
    INTEXPECT([reader cputype], CPU_TYPE_ARM64, ([NSString stringWithFormat:@"%@ should be arm64", name]));
}

// Verifies required load commands - same for both
+(void)verifyRequiredLoadCommands:(MPWMachOReader*)reader name:(NSString*)name
{
    EXPECTNOTNIL([reader loadCommandOfTypeIfPresent:LC_ID_DYLIB], ([NSString stringWithFormat:@"%@ should have LC_ID_DYLIB", name]));
    EXPECTNOTNIL([reader loadCommandOfTypeIfPresent:LC_SYMTAB], ([NSString stringWithFormat:@"%@ should have LC_SYMTAB", name]));
    EXPECTNOTNIL([reader loadCommandOfTypeIfPresent:LC_DYSYMTAB], ([NSString stringWithFormat:@"%@ should have LC_DYSYMTAB", name]));
    EXPECTNOTNIL([reader loadCommandOfTypeIfPresent:LC_UUID], ([NSString stringWithFormat:@"%@ should have LC_UUID", name]));
    EXPECTNOTNIL([reader loadCommandOfTypeIfPresent:LC_BUILD_VERSION], ([NSString stringWithFormat:@"%@ should have LC_BUILD_VERSION", name]));
    EXPECTNOTNIL([reader loadCommandOfTypeIfPresent:LC_LOAD_DYLIB], ([NSString stringWithFormat:@"%@ should have LC_LOAD_DYLIB", name]));
}

// Verifies segment layout - same structure, different details
+(void)verifySegmentLayout:(MPWMachOReader*)reader name:(NSString*)name
{
    struct segment_command_64 *text = [reader segmentNamed:@"__TEXT"];
    struct segment_command_64 *linkedit = [reader segmentNamed:@"__LINKEDIT"];

    EXPECTNOTNIL((id)(uintptr_t)text, ([NSString stringWithFormat:@"%@ should have __TEXT segment", name]));
    EXPECTNOTNIL((id)(uintptr_t)linkedit, ([NSString stringWithFormat:@"%@ should have __LINKEDIT segment", name]));

    // __TEXT starts at 0
    INTEXPECT(text->fileoff, 0, ([NSString stringWithFormat:@"%@ __TEXT should start at file offset 0", name]));
    INTEXPECT(text->vmaddr, 0, ([NSString stringWithFormat:@"%@ __TEXT should start at vmaddr 0", name]));

    // __TEXT vmsize should be page-aligned
    INTEXPECT(text->vmsize % 0x4000, 0, ([NSString stringWithFormat:@"%@ __TEXT vmsize should be 16KB aligned", name]));

    // File size should match __LINKEDIT end
    long expectedFileSize = linkedit->fileoff + linkedit->filesize;
    INTEXPECT((long)reader.data.length, expectedFileSize, ([NSString stringWithFormat:@"%@ file size should match __LINKEDIT end", name]));
}

// Verifies class symbols are exported - parameterized by class name
+(void)verifyExportsClassSymbols:(MPWMachOReader*)reader className:(NSString*)className name:(NSString*)name
{
    NSArray *exports = [reader exportedSymbolNames];

    NSString *classSymbol = [NSString stringWithFormat:@"_OBJC_CLASS_$_%@", className];
    NSString *metaclassSymbol = [NSString stringWithFormat:@"_OBJC_METACLASS_$_%@", className];

    EXPECTTRUE([exports containsObject:classSymbol], ([NSString stringWithFormat:@"%@ should export %@", name, classSymbol]));
    EXPECTTRUE([exports containsObject:metaclassSymbol], ([NSString stringWithFormat:@"%@ should export %@", name, metaclassSymbol]));
}

// Logs all segments and sections for debugging
+(void)logSegmentsAndSections:(MPWMachOReader*)reader name:(NSString*)name
{
    const struct mach_header_64 *header = (const struct mach_header_64 *)reader.data.bytes;
    const uint8_t *ptr = (const uint8_t *)(header + 1);

    NSLog(@"%@ segments and sections:", name);
    for (uint32_t i = 0; i < header->ncmds; i++) {
        const struct load_command *cmd = (const struct load_command *)ptr;
        if (cmd->cmd == LC_SEGMENT_64) {
            const struct segment_command_64 *seg = (const struct segment_command_64 *)ptr;
            NSLog(@"  Segment '%.16s': vmaddr=0x%llx vmsize=0x%llx fileoff=%lld filesize=%lld",
                  seg->segname, seg->vmaddr, seg->vmsize, seg->fileoff, seg->filesize);

            const struct section_64 *sections = (const struct section_64 *)(seg + 1);
            for (uint32_t j = 0; j < seg->nsects; j++) {
                NSLog(@"    Section '%.16s': addr=0x%llx size=%lld offset=%d flags=0x%x",
                      sections[j].sectname, sections[j].addr, sections[j].size,
                      sections[j].offset, sections[j].flags);
            }
        }
        ptr += cmd->cmdsize;
    }
}

#pragma mark - Object File Analysis

+(void)testObjectFileSections
{
    NSURL *objectURL = [[self testBundle] URLForResource:@"ReferenceSTClass" withExtension:@"macho"];
    if (!objectURL) {
        NSLog(@"Object file not found in bundle");
        return;
    }

    NSData *objectData = [NSData dataWithContentsOfURL:objectURL];
    MPWMachOReader *reader = [[[MPWMachOReader alloc] initWithData:objectData] autorelease];

    const struct mach_header_64 *header = (const struct mach_header_64 *)reader.data.bytes;
    const uint8_t *ptr = (const uint8_t *)(header + 1);

    NSLog(@"Object file (.o) segments and sections:");
    for (uint32_t i = 0; i < header->ncmds; i++) {
        const struct load_command *cmd = (const struct load_command *)ptr;
        if (cmd->cmd == LC_SEGMENT_64) {
            const struct segment_command_64 *seg = (const struct segment_command_64 *)ptr;
            NSLog(@"  Segment '%.16s': vmaddr=0x%llx vmsize=0x%llx fileoff=%lld filesize=%lld",
                  seg->segname, seg->vmaddr, seg->vmsize, seg->fileoff, seg->filesize);

            const struct section_64 *sections = (const struct section_64 *)(seg + 1);
            for (uint32_t j = 0; j < seg->nsects; j++) {
                NSLog(@"    Section '%.16s,%.16s': addr=0x%llx size=%lld offset=%d flags=0x%x",
                      sections[j].segname, sections[j].sectname,
                      sections[j].addr, sections[j].size, sections[j].offset, sections[j].flags);
            }
        }
        ptr += cmd->cmdsize;
    }
}

#pragma mark - Reference Framework Test

+(void)verifyFixupFormat:(MPWMachOReader*)reader name:(NSString*)name usesChainedFixups:(BOOL)expectChained
{
    BOOL hasChainedFixups = [reader loadCommandOfTypeIfPresent:LC_DYLD_CHAINED_FIXUPS] != NULL;
    BOOL hasDyldInfo = [reader loadCommandOfTypeIfPresent:LC_DYLD_INFO_ONLY] != NULL;

    NSLog(@"%@ fixup format: %@", name,
          hasChainedFixups ? @"LC_DYLD_CHAINED_FIXUPS" :
          hasDyldInfo ? @"LC_DYLD_INFO_ONLY" : @"unknown");

    EXPECTTRUE(hasChainedFixups || hasDyldInfo,
               ([NSString stringWithFormat:@"%@ should have fixup info", name]));

    if (hasDyldInfo) {
        const struct dyld_info_command *dyldInfo =
            (const struct dyld_info_command*)[reader loadCommandOfTypeIfPresent:LC_DYLD_INFO_ONLY];
        NSLog(@"%@ bind info: rebase_size=%d bind_size=%d export_size=%d", name,
              dyldInfo->rebase_size, dyldInfo->bind_size, dyldInfo->export_size);
    }
}

+(void)verifyDataConstSegment:(MPWMachOReader*)reader name:(NSString*)name
{
    struct segment_command_64 *text = [reader segmentNamed:@"__TEXT"];
    struct segment_command_64 *dataConst = [reader segmentNamed:@"__DATA_CONST"];
    struct segment_command_64 *data = [reader segmentNamed:@"__DATA"];
    struct segment_command_64 *linkedit = [reader segmentNamed:@"__LINKEDIT"];

    EXPECTNOTNIL((id)(uintptr_t)dataConst,
                 ([NSString stringWithFormat:@"%@ should have __DATA_CONST segment", name]));

    if (dataConst) {
        // __DATA_CONST should come right after __TEXT
        INTEXPECT(dataConst->vmaddr, text->vmsize,
                  ([NSString stringWithFormat:@"%@ __DATA_CONST vmaddr should follow __TEXT", name]));

        // Track expected vmaddr
        long expectedVmaddr = dataConst->vmaddr + dataConst->vmsize;

        // __DATA should come after __DATA_CONST
        if (data) {
            INTEXPECT(data->vmaddr, expectedVmaddr,
                      ([NSString stringWithFormat:@"%@ __DATA vmaddr should follow __DATA_CONST", name]));
            expectedVmaddr += data->vmsize;
        }

        // __LINKEDIT should come last
        INTEXPECT(linkedit->vmaddr, expectedVmaddr,
                  ([NSString stringWithFormat:@"%@ __LINKEDIT vmaddr should follow all data segments", name]));
    }
}

+(int)countSegments:(MPWMachOReader*)reader
{
    int count = 0;
    const struct mach_header_64 *header = (const struct mach_header_64 *)reader.data.bytes;
    const uint8_t *ptr = (const uint8_t *)(header + 1);
    for (uint32_t i = 0; i < header->ncmds; i++) {
        const struct load_command *cmd = (const struct load_command *)ptr;
        if (cmd->cmd == LC_SEGMENT_64) count++;
        ptr += cmd->cmdsize;
    }
    return count;
}

// Single test for the reference (externally linked) dylib
+(void)testReferenceDylib
{
    MPWMachOReader *reader = [self readerForReferenceFramework];
    if (!reader) {
        NSLog(@"Reference framework not available");
        return;
    }

    [self logSegmentsAndSections:reader name:@"Reference"];
    [self verifyValidMachO:reader name:@"Reference"];
    [self verifyRequiredLoadCommands:reader name:@"Reference"];
    [self verifySegmentLayout:reader name:@"Reference"];
    [self verifyExportsClassSymbols:reader className:@"ReferenceSTClass" name:@"Reference"];
    [self verifyFixupFormat:reader name:@"Reference" usesChainedFixups:YES];
    [self verifyDataConstSegment:reader name:@"Reference"];
}

#pragma mark - Internal Linker Test

// Single test for the internally linked dylib
+(void)testInternalLinkerDylib
{
    MPWMachOReader *reader = [self readerForInternalLinkerDylib];

    [self logSegmentsAndSections:reader name:@"Internal"];
    [self verifyValidMachO:reader name:@"Internal"];
    [self verifyRequiredLoadCommands:reader name:@"Internal"];
    [self verifySegmentLayout:reader name:@"Internal"];
    [self verifyExportsClassSymbols:reader className:@"InternalLinkerTestClass" name:@"Internal"];
    [self verifyFixupFormat:reader name:@"Internal" usesChainedFixups:NO];
    [self verifyDataConstSegment:reader name:@"Internal"];
}

#pragma mark - Comparison Tests

+(void)testCompareReferenceAndInternal
{
    MPWMachOReader *ref = [self readerForReferenceFramework];
    MPWMachOReader *internal = [self readerForInternalLinkerDylib];
    if (!ref) return;

    int refSegments = [self countSegments:ref];
    int internalSegments = [self countSegments:internal];

    NSLog(@"Segment count: reference=%d internal=%d", refSegments, internalSegments);
    INTEXPECT(internalSegments, refSegments, @"Should have same number of segments as reference");
}

+(NSArray*)testSelectors
{
    return @[
        @"testObjectFileSections",
        @"testReferenceDylib",
        @"testInternalLinkerDylib",
        @"testCompareReferenceAndInternal",
    ];
}

@end
