//
//  MPWMachOLinkerCharacterizationTests.m
//  ObjSTNative
//
//  Characterization tests for dylib generation
//  These tests compare our internal linker output against reference dylibs
//  generated by the external linker.
//

#import <MPWFoundation/MPWFoundation.h>
#import "MPWMachOReader.h"
#import "MPWMachOLinker.h"
#import "MPWMachODylibWriter.h"
#import "STNativeCompiler.h"
#import <mach-o/loader.h>

@interface MPWMachOLinkerCharacterizationTests : NSObject
@end

@implementation MPWMachOLinkerCharacterizationTests

#pragma mark - Helper Methods

+(void)codesignDylibAtPath:(NSString*)path
{
    NSTask *task = [[[NSTask alloc] init] autorelease];
    task.launchPath = @"/usr/bin/codesign";
    task.arguments = @[@"-f", @"-s", @"-", path];
    task.standardOutput = [NSPipe pipe];
    task.standardError = [NSPipe pipe];
    [task launch];
    [task waitUntilExit];
}

+(NSBundle*)testBundle
{
    return [NSBundle bundleForClass:self];
}

+(NSURL*)referenceFrameworkURL
{
    return [[self testBundle] URLForResource:@"ReferenceSTClass" withExtension:@"framework"];
}

+(MPWMachOReader*)readerForReferenceFramework
{
    NSURL *frameworkURL = [self referenceFrameworkURL];
    if (!frameworkURL) return nil;

    NSString *dylibPath = [[frameworkURL path] stringByAppendingPathComponent:@"ReferenceSTClass"];
    NSData *data = [NSData dataWithContentsOfFile:dylibPath];
    if (!data) return nil;

    return [[[MPWMachOReader alloc] initWithData:data] autorelease];
}

#pragma mark - Reference Framework Generation

// This test generates the reference framework
// Run it once manually: testlogger ObjSTNative MPWMachOLinkerCharacterizationTests testGenerateReferenceFramework
// Then verify it works and copy to ObjSTNative/Resources/
+(void)testGenerateReferenceFramework
{
    // Compile a simple ST class
    STNativeCompiler *compiler = [STNativeCompiler compiler];
    NSString *source = @"class ReferenceSTClass : NSObject { -<int>answerFortyTwo { 42. } -<int>addFive:x { x + 5. } }";
    STClassDefinition *theClass = [compiler compile:source];
    NSData *objectData = [compiler compileClassToMachoO:theClass];

    // Write object file
    NSString *objectPath = @"/tmp/ReferenceSTClass.o";
    [objectData writeToFile:objectPath atomically:YES];

    // Create framework directory structure
    NSString *frameworkDir = @"/tmp/ReferenceSTClass.framework";
    [[NSFileManager defaultManager] removeItemAtPath:frameworkDir error:nil];
    [[NSFileManager defaultManager] createDirectoryAtPath:frameworkDir
                              withIntermediateDirectories:YES
                                               attributes:nil
                                                    error:nil];

    // Link with external linker
    NSString *dylibPath = [frameworkDir stringByAppendingPathComponent:@"ReferenceSTClass"];
    NSString *ldCommand = [NSString stringWithFormat:
        @"ld -dylib -arch arm64 "
        @"-platform_version macos 11.0.0 14.0 "
        @"-syslibroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk "
        @"-o %@ %@ "
        @"-lSystem "
        @"-F/Library/Frameworks -framework Foundation -framework ObjectiveSmalltalk -framework MPWFoundation "
        @"-install_name @rpath/ReferenceSTClass.framework/ReferenceSTClass",
        dylibPath, objectPath];
    int result = system([ldCommand UTF8String]);

    if (result == 0) {
        // Sign the framework
        [self codesignDylibAtPath:dylibPath];
        NSLog(@"Reference framework generated at: %@", frameworkDir);
        NSLog(@"Verify it works with: st -e 'framework:ReferenceSTClass. class:ReferenceSTClass new answerFortyTwo.'");
        NSLog(@"Then copy to ObjSTNative/Resources/");
    } else {
        NSLog(@"Failed to link reference framework");
    }
}

#pragma mark - Characterization Tests for Reference Dylib

// These tests document the structure of a known-good dylib
+(void)testReferenceFrameworkExists
{
    NSURL *url = [self referenceFrameworkURL];
    // This test will fail until the reference framework is added to Resources
    // Run generateReferenceFramework, verify it works, then add it
    if (!url) {
        NSLog(@"Reference framework not found. Run generateReferenceFramework to create it.");
    }
    // Don't fail - this is expected initially
    EXPECTTRUE(YES, @"placeholder");
}

+(void)testReferenceDylibIsValidMachO
{
    MPWMachOReader *reader = [self readerForReferenceFramework];
    if (!reader) {
        NSLog(@"Skipping - reference framework not available");
        return;
    }

    EXPECTTRUE(reader.isHeaderValid, @"reference dylib should be valid Mach-O");
    INTEXPECT([reader filetype], MH_DYLIB, @"should be a dylib");
    INTEXPECT([reader cputype], CPU_TYPE_ARM64, @"should be arm64");
}

+(void)testReferenceDylibHasRequiredSegments
{
    MPWMachOReader *reader = [self readerForReferenceFramework];
    if (!reader) return;

    // Iterate through all load commands to find ALL segments and their sections
    const struct mach_header_64 *header = (const struct mach_header_64 *)reader.data.bytes;
    const uint8_t *ptr = (const uint8_t *)(header + 1);

    NSLog(@"Reference dylib segments and sections:");
    for (uint32_t i = 0; i < header->ncmds; i++) {
        const struct load_command *cmd = (const struct load_command *)ptr;
        if (cmd->cmd == LC_SEGMENT_64) {
            const struct segment_command_64 *seg = (const struct segment_command_64 *)ptr;
            NSLog(@"  Segment '%.16s': vmaddr=0x%llx vmsize=0x%llx fileoff=%lld filesize=%lld",
                  seg->segname, seg->vmaddr, seg->vmsize, seg->fileoff, seg->filesize);

            // List sections in this segment
            const struct section_64 *sections = (const struct section_64 *)(seg + 1);
            for (uint32_t j = 0; j < seg->nsects; j++) {
                NSLog(@"    Section '%.16s': addr=0x%llx size=%lld offset=%d flags=0x%x",
                      sections[j].sectname, sections[j].addr, sections[j].size,
                      sections[j].offset, sections[j].flags);
            }
        }
        ptr += cmd->cmdsize;
    }

    struct segment_command_64 *text = [reader segmentNamed:@"__TEXT"];
    struct segment_command_64 *linkedit = [reader segmentNamed:@"__LINKEDIT"];

    EXPECTNOTNIL((id)(uintptr_t)text, @"should have __TEXT segment");
    EXPECTNOTNIL((id)(uintptr_t)linkedit, @"should have __LINKEDIT segment");
}

+(void)testReferenceDylibHasRequiredLoadCommands
{
    MPWMachOReader *reader = [self readerForReferenceFramework];
    if (!reader) return;

    EXPECTNOTNIL([reader loadCommandOfTypeIfPresent:LC_ID_DYLIB], @"should have LC_ID_DYLIB");
    EXPECTNOTNIL([reader loadCommandOfTypeIfPresent:LC_SYMTAB], @"should have LC_SYMTAB");
    EXPECTNOTNIL([reader loadCommandOfTypeIfPresent:LC_DYSYMTAB], @"should have LC_DYSYMTAB");
    EXPECTNOTNIL([reader loadCommandOfTypeIfPresent:LC_UUID], @"should have LC_UUID");
    EXPECTNOTNIL([reader loadCommandOfTypeIfPresent:LC_BUILD_VERSION], @"should have LC_BUILD_VERSION");
    EXPECTNOTNIL([reader loadCommandOfTypeIfPresent:LC_LOAD_DYLIB], @"should have LC_LOAD_DYLIB");

    // Check for exports - either LC_DYLD_EXPORTS_TRIE or LC_DYLD_INFO_ONLY
    BOOL hasExports = [reader loadCommandOfTypeIfPresent:LC_DYLD_EXPORTS_TRIE] != NULL ||
                      [reader loadCommandOfTypeIfPresent:LC_DYLD_INFO_ONLY] != NULL;
    EXPECTTRUE(hasExports, @"should have exports trie");
}

+(void)testReferenceDylibExportsClassSymbols
{
    MPWMachOReader *reader = [self readerForReferenceFramework];
    if (!reader) return;

    NSArray *exports = [reader exportedSymbolNames];
    NSLog(@"Reference exports: %@", exports);

    EXPECTTRUE([exports containsObject:@"_OBJC_CLASS_$_ReferenceSTClass"], @"should export class symbol");
    EXPECTTRUE([exports containsObject:@"_OBJC_METACLASS_$_ReferenceSTClass"], @"should export metaclass symbol");
}

+(void)testReferenceDylibBindInfo
{
    MPWMachOReader *reader = [self readerForReferenceFramework];
    if (!reader) return;

    // Check for LC_DYLD_INFO_ONLY which contains bind info
    const struct dyld_info_command *dyldInfo =
        (const struct dyld_info_command*)[reader loadCommandOfTypeIfPresent:LC_DYLD_INFO_ONLY];

    if (dyldInfo) {
        NSLog(@"Reference bind info: rebase_size=%d bind_size=%d export_size=%d",
              dyldInfo->rebase_size, dyldInfo->bind_size, dyldInfo->export_size);

        // Document the sizes we observe
        EXPECTTRUE(dyldInfo->bind_size > 0, @"should have bind data");
    } else {
        NSLog(@"Reference uses LC_DYLD_CHAINED_FIXUPS (modern format)");
    }
}

#pragma mark - Object File Analysis

+(void)testObjectFileSections
{
    // Read the object file that was used to generate the reference framework
    NSURL *objectURL = [[self testBundle] URLForResource:@"ReferenceSTClass" withExtension:@"macho"];
    if (!objectURL) {
        NSLog(@"Object file not found in bundle");
        return;
    }

    NSData *objectData = [NSData dataWithContentsOfURL:objectURL];
    MPWMachOReader *reader = [[[MPWMachOReader alloc] initWithData:objectData] autorelease];

    const struct mach_header_64 *header = (const struct mach_header_64 *)reader.data.bytes;
    const uint8_t *ptr = (const uint8_t *)(header + 1);

    NSLog(@"Object file (.o) segments and sections:");
    for (uint32_t i = 0; i < header->ncmds; i++) {
        const struct load_command *cmd = (const struct load_command *)ptr;
        if (cmd->cmd == LC_SEGMENT_64) {
            const struct segment_command_64 *seg = (const struct segment_command_64 *)ptr;
            NSLog(@"  Segment '%.16s': vmaddr=0x%llx vmsize=0x%llx fileoff=%lld filesize=%lld",
                  seg->segname, seg->vmaddr, seg->vmsize, seg->fileoff, seg->filesize);

            const struct section_64 *sections = (const struct section_64 *)(seg + 1);
            for (uint32_t j = 0; j < seg->nsects; j++) {
                NSLog(@"    Section '%.16s,%.16s': addr=0x%llx size=%lld offset=%d flags=0x%x",
                      sections[j].segname, sections[j].sectname,
                      sections[j].addr, sections[j].size, sections[j].offset, sections[j].flags);
            }
        }
        ptr += cmd->cmdsize;
    }
}

#pragma mark - Internal Linker Output Tests

+(NSData*)generateInternalLinkerDylib
{
    STNativeCompiler *compiler = [STNativeCompiler compiler];
    NSString *source = @"class InternalLinkerTestClass : NSObject { -answerFortyTwo { 42. } -addFive:x { x + 5. } }";
    STClassDefinition *theClass = [compiler compile:source];
    [compiler compileClassToMachoO:theClass];

    MPWMachOLinker *linker = [[[MPWMachOLinker alloc] init] autorelease];
    return [linker linkToDylibWithInstallName:@"@rpath/InternalLinkerTestClass.framework/InternalLinkerTestClass"
                                   fromWriter:(MPWMachOWriter*)compiler.writer];
}

+(void)testInternalLinkerProducesValidMachO
{
    NSData *dylib = [self generateInternalLinkerDylib];
    MPWMachOReader *reader = [[[MPWMachOReader alloc] initWithData:dylib] autorelease];

    EXPECTTRUE(reader.isHeaderValid, @"internal linker should produce valid Mach-O");
    INTEXPECT([reader filetype], MH_DYLIB, @"should be a dylib");
    INTEXPECT([reader cputype], CPU_TYPE_ARM64, @"should be arm64");
}

+(void)testInternalLinkerHasRequiredSegments
{
    NSData *dylib = [self generateInternalLinkerDylib];
    MPWMachOReader *reader = [[[MPWMachOReader alloc] initWithData:dylib] autorelease];

    // Show all segments and sections like we did for reference
    const struct mach_header_64 *header = (const struct mach_header_64 *)reader.data.bytes;
    const uint8_t *ptr = (const uint8_t *)(header + 1);

    NSLog(@"Internal linker dylib segments and sections:");
    for (uint32_t i = 0; i < header->ncmds; i++) {
        const struct load_command *cmd = (const struct load_command *)ptr;
        if (cmd->cmd == LC_SEGMENT_64) {
            const struct segment_command_64 *seg = (const struct segment_command_64 *)ptr;
            NSLog(@"  Segment '%.16s': vmaddr=0x%llx vmsize=0x%llx fileoff=%lld filesize=%lld",
                  seg->segname, seg->vmaddr, seg->vmsize, seg->fileoff, seg->filesize);

            const struct section_64 *sections = (const struct section_64 *)(seg + 1);
            for (uint32_t j = 0; j < seg->nsects; j++) {
                NSLog(@"    Section '%.16s': addr=0x%llx size=%lld offset=%d flags=0x%x",
                      sections[j].sectname, sections[j].addr, sections[j].size,
                      sections[j].offset, sections[j].flags);
            }
        }
        ptr += cmd->cmdsize;
    }

    struct segment_command_64 *text = [reader segmentNamed:@"__TEXT"];
    struct segment_command_64 *linkedit = [reader segmentNamed:@"__LINKEDIT"];

    EXPECTNOTNIL((id)(uintptr_t)text, @"should have __TEXT segment");
    EXPECTNOTNIL((id)(uintptr_t)linkedit, @"should have __LINKEDIT segment");
}

+(void)testInternalLinkerHasRequiredLoadCommands
{
    NSData *dylib = [self generateInternalLinkerDylib];
    MPWMachOReader *reader = [[[MPWMachOReader alloc] initWithData:dylib] autorelease];

    EXPECTNOTNIL([reader loadCommandOfTypeIfPresent:LC_ID_DYLIB], @"should have LC_ID_DYLIB");
    EXPECTNOTNIL([reader loadCommandOfTypeIfPresent:LC_SYMTAB], @"should have LC_SYMTAB");
    EXPECTNOTNIL([reader loadCommandOfTypeIfPresent:LC_DYSYMTAB], @"should have LC_DYSYMTAB");
    EXPECTNOTNIL([reader loadCommandOfTypeIfPresent:LC_UUID], @"should have LC_UUID");
    EXPECTNOTNIL([reader loadCommandOfTypeIfPresent:LC_BUILD_VERSION], @"should have LC_BUILD_VERSION");
    EXPECTNOTNIL([reader loadCommandOfTypeIfPresent:LC_LOAD_DYLIB], @"should have LC_LOAD_DYLIB");

    // Our linker uses LC_DYLD_INFO_ONLY
    EXPECTNOTNIL([reader loadCommandOfTypeIfPresent:LC_DYLD_INFO_ONLY], @"should have LC_DYLD_INFO_ONLY");
}

+(void)testInternalLinkerExportsClassSymbols
{
    NSData *dylib = [self generateInternalLinkerDylib];
    MPWMachOReader *reader = [[[MPWMachOReader alloc] initWithData:dylib] autorelease];

    NSArray *exports = [reader exportedSymbolNames];
    NSLog(@"Internal exports: %@", exports);

    EXPECTTRUE([exports containsObject:@"_OBJC_CLASS_$_InternalLinkerTestClass"], @"should export class symbol");
    EXPECTTRUE([exports containsObject:@"_OBJC_METACLASS_$_InternalLinkerTestClass"], @"should export metaclass symbol");
}

+(void)testInternalLinkerBindInfo
{
    NSData *dylib = [self generateInternalLinkerDylib];
    MPWMachOReader *reader = [[[MPWMachOReader alloc] initWithData:dylib] autorelease];

    const struct dyld_info_command *dyldInfo =
        (const struct dyld_info_command*)[reader loadCommandOfTypeIfPresent:LC_DYLD_INFO_ONLY];

    EXPECTNOTNIL((id)(uintptr_t)dyldInfo, @"should have LC_DYLD_INFO_ONLY");

    if (dyldInfo) {
        NSLog(@"Internal bind info: rebase_size=%d bind_size=%d export_size=%d",
              dyldInfo->rebase_size, dyldInfo->bind_size, dyldInfo->export_size);

        EXPECTTRUE(dyldInfo->rebase_size > 0, @"should have rebase data");
        EXPECTTRUE(dyldInfo->bind_size > 0, @"should have bind data");
        EXPECTTRUE(dyldInfo->export_size > 0, @"should have export data");
    }
}

+(void)testInternalLinkerSegmentLayoutIsValid
{
    NSData *dylib = [self generateInternalLinkerDylib];
    MPWMachOReader *reader = [[[MPWMachOReader alloc] initWithData:dylib] autorelease];

    struct segment_command_64 *text = [reader segmentNamed:@"__TEXT"];
    struct segment_command_64 *dataConst = [reader segmentNamed:@"__DATA_CONST"];
    struct segment_command_64 *data = [reader segmentNamed:@"__DATA"];
    struct segment_command_64 *linkedit = [reader segmentNamed:@"__LINKEDIT"];

    // Verify layout constraints
    INTEXPECT(text->fileoff, 0, @"__TEXT should start at file offset 0");
    INTEXPECT(text->vmaddr, 0, @"__TEXT should start at vmaddr 0");

    // __TEXT vmsize should be page-aligned
    INTEXPECT(text->vmsize % 0x4000, 0, @"__TEXT vmsize should be 16KB aligned");

    // Track expected vmaddr for subsequent segments
    long expectedVmaddr = text->vmsize;

    // __DATA_CONST should come after __TEXT (if present)
    if (dataConst) {
        EXPECTTRUE(dataConst->fileoff >= text->filesize, @"__DATA_CONST should come after __TEXT in file");
        INTEXPECT(dataConst->vmaddr, expectedVmaddr, @"__DATA_CONST vmaddr should follow __TEXT");
        expectedVmaddr += dataConst->vmsize;
    }

    // __DATA should come after __DATA_CONST (or __TEXT if no __DATA_CONST)
    if (data) {
        INTEXPECT(data->vmaddr, expectedVmaddr, @"__DATA vmaddr should follow previous segment");
        expectedVmaddr += data->vmsize;
    }

    // __LINKEDIT should come last
    INTEXPECT(linkedit->vmaddr, expectedVmaddr, @"__LINKEDIT vmaddr should follow previous segment");

    // File size should match __LINKEDIT end
    long expectedFileSize = linkedit->fileoff + linkedit->filesize;
    INTEXPECT((long)dylib.length, expectedFileSize, @"file size should match __LINKEDIT end");
}

+(NSArray*)testSelectors
{
    return @[
        // Object file analysis
        @"testObjectFileSections",
        // Reference framework tests
        @"testReferenceFrameworkExists",
        @"testReferenceDylibIsValidMachO",
        @"testReferenceDylibHasRequiredSegments",
        @"testReferenceDylibHasRequiredLoadCommands",
        @"testReferenceDylibExportsClassSymbols",
        @"testReferenceDylibBindInfo",
        // Internal linker tests
        @"testInternalLinkerProducesValidMachO",
        @"testInternalLinkerHasRequiredSegments",
        @"testInternalLinkerHasRequiredLoadCommands",
        @"testInternalLinkerExportsClassSymbols",
        @"testInternalLinkerBindInfo",
        @"testInternalLinkerSegmentLayoutIsValid",
    ];
}

@end
